---
# Nginx

- name: Template nginx.repo
  template: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo mode=0644

- name: install Nginx
  yum: pkg={{ item }} state=installed enablerepo=nginx
  with_items:
    - nginx

- name: insert iptables rule
  lineinfile:
    dest=/etc/nginx/nginx.conf
    regexp="^\\s+worker_connections "
    line="    worker_connections  {{worker_connections}};"

- name: ensure nginx is running automatically at boot time
  service: name=nginx state=restarted enabled=yes

- name: insert iptables rule
  command: firewall-cmd --add-port "{{ www_port }}/tcp" --permanent

