- name: Install MariaDB
  yum: pkg={{ item }} state=present
  with_items:
    - mariadb
    - mariadb-server
    - mariadb-devel
    - MySQL-python

- name: mariadb service enable and start
  service: name=mariadb state=started enabled=yes
